name: wazo-stt
namespace: quintana
version: 0.3.0
author: Sylvain Boily
display_name: STT voice module
plugin_format_version: 1
tags:
  - application
  - AI
  - Voice transcription
homepage: http://github.com/sboily
